// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangePassword(arg1, arg2, arg3) {
  return window['go']['main']['App']['ChangePassword'](arg1, arg2, arg3);
}

export function CreateClass(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['main']['App']['CreateClass'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}

export function CreateDepartment(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateDepartment'](arg1, arg2, arg3);
}

export function CreateSubject(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateSubject'](arg1, arg2, arg3, arg4);
}

export function CreateUser(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14) {
  return window['go']['main']['App']['CreateUser'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14);
}

export function CreateUsersBulk(arg1) {
  return window['go']['main']['App']['CreateUsersBulk'](arg1);
}

export function CreateUsersBulkFromFile(arg1, arg2) {
  return window['go']['main']['App']['CreateUsersBulkFromFile'](arg1, arg2);
}

export function DeleteClass(arg1) {
  return window['go']['main']['App']['DeleteClass'](arg1);
}

export function DeleteDepartment(arg1) {
  return window['go']['main']['App']['DeleteDepartment'](arg1);
}

export function DeleteUser(arg1) {
  return window['go']['main']['App']['DeleteUser'](arg1);
}

export function EnrollMultipleStudents(arg1, arg2, arg3) {
  return window['go']['main']['App']['EnrollMultipleStudents'](arg1, arg2, arg3);
}

export function EnrollStudentInClass(arg1, arg2, arg3) {
  return window['go']['main']['App']['EnrollStudentInClass'](arg1, arg2, arg3);
}

export function ExportAttendanceCSV(arg1) {
  return window['go']['main']['App']['ExportAttendanceCSV'](arg1);
}

export function ExportFeedbackCSV() {
  return window['go']['main']['App']['ExportFeedbackCSV']();
}

export function ExportFeedbackPDF() {
  return window['go']['main']['App']['ExportFeedbackPDF']();
}

export function ExportLogsCSV() {
  return window['go']['main']['App']['ExportLogsCSV']();
}

export function ExportLogsPDF() {
  return window['go']['main']['App']['ExportLogsPDF']();
}

export function ForwardFeedbackToAdmin(arg1, arg2, arg3) {
  return window['go']['main']['App']['ForwardFeedbackToAdmin'](arg1, arg2, arg3);
}

export function ForwardMultipleFeedbackToAdmin(arg1, arg2, arg3) {
  return window['go']['main']['App']['ForwardMultipleFeedbackToAdmin'](arg1, arg2, arg3);
}

export function GenerateAttendanceFromLogs(arg1, arg2, arg3) {
  return window['go']['main']['App']['GenerateAttendanceFromLogs'](arg1, arg2, arg3);
}

export function GetAdminDashboard() {
  return window['go']['main']['App']['GetAdminDashboard']();
}

export function GetAllClasses() {
  return window['go']['main']['App']['GetAllClasses']();
}

export function GetAllLogs() {
  return window['go']['main']['App']['GetAllLogs']();
}

export function GetAllRegisteredStudents(arg1, arg2) {
  return window['go']['main']['App']['GetAllRegisteredStudents'](arg1, arg2);
}

export function GetAllStudentsForEnrollment(arg1) {
  return window['go']['main']['App']['GetAllStudentsForEnrollment'](arg1);
}

export function GetAllTeachers() {
  return window['go']['main']['App']['GetAllTeachers']();
}

export function GetAvailableSections() {
  return window['go']['main']['App']['GetAvailableSections']();
}

export function GetAvailableStudents(arg1) {
  return window['go']['main']['App']['GetAvailableStudents'](arg1);
}

export function GetClassAttendance(arg1, arg2) {
  return window['go']['main']['App']['GetClassAttendance'](arg1, arg2);
}

export function GetClassStudents(arg1) {
  return window['go']['main']['App']['GetClassStudents'](arg1);
}

export function GetClassesByCreator(arg1) {
  return window['go']['main']['App']['GetClassesByCreator'](arg1);
}

export function GetClassesBySubjectCode(arg1) {
  return window['go']['main']['App']['GetClassesBySubjectCode'](arg1);
}

export function GetDepartments() {
  return window['go']['main']['App']['GetDepartments']();
}

export function GetFeedback() {
  return window['go']['main']['App']['GetFeedback']();
}

export function GetPendingFeedback() {
  return window['go']['main']['App']['GetPendingFeedback']();
}

export function GetStudentClasses(arg1) {
  return window['go']['main']['App']['GetStudentClasses'](arg1);
}

export function GetStudentDashboard(arg1) {
  return window['go']['main']['App']['GetStudentDashboard'](arg1);
}

export function GetStudentFeedback(arg1) {
  return window['go']['main']['App']['GetStudentFeedback'](arg1);
}

export function GetStudentLoginLogs(arg1) {
  return window['go']['main']['App']['GetStudentLoginLogs'](arg1);
}

export function GetSubjects() {
  return window['go']['main']['App']['GetSubjects']();
}

export function GetTeacherClasses(arg1) {
  return window['go']['main']['App']['GetTeacherClasses'](arg1);
}

export function GetTeacherClassesByUserID(arg1) {
  return window['go']['main']['App']['GetTeacherClassesByUserID'](arg1);
}

export function GetTeacherClassesCreatedByWorkingStudents(arg1) {
  return window['go']['main']['App']['GetTeacherClassesCreatedByWorkingStudents'](arg1);
}

export function GetTeacherDashboard(arg1) {
  return window['go']['main']['App']['GetTeacherDashboard'](arg1);
}

export function GetTeacherID(arg1) {
  return window['go']['main']['App']['GetTeacherID'](arg1);
}

export function GetUsers() {
  return window['go']['main']['App']['GetUsers']();
}

export function GetUsersByType(arg1) {
  return window['go']['main']['App']['GetUsersByType'](arg1);
}

export function GetWorkingStudentDashboard() {
  return window['go']['main']['App']['GetWorkingStudentDashboard']();
}

export function GetWorkingStudentID(arg1) {
  return window['go']['main']['App']['GetWorkingStudentID'](arg1);
}

export function InitializeAttendanceForClass(arg1, arg2, arg3) {
  return window['go']['main']['App']['InitializeAttendanceForClass'](arg1, arg2, arg3);
}

export function JoinClassBySubjectCode(arg1, arg2) {
  return window['go']['main']['App']['JoinClassBySubjectCode'](arg1, arg2);
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout(arg1) {
  return window['go']['main']['App']['Logout'](arg1);
}

export function RecordAttendance(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['RecordAttendance'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function RecordStudentLogin(arg1, arg2, arg3) {
  return window['go']['main']['App']['RecordStudentLogin'](arg1, arg2, arg3);
}

export function RecordTimeoutLogout(arg1) {
  return window['go']['main']['App']['RecordTimeoutLogout'](arg1);
}

export function SaveEquipmentFeedback(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11) {
  return window['go']['main']['App']['SaveEquipmentFeedback'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
}

export function SearchUsers(arg1, arg2) {
  return window['go']['main']['App']['SearchUsers'](arg1, arg2);
}

export function UnenrollStudentFromClass(arg1) {
  return window['go']['main']['App']['UnenrollStudentFromClass'](arg1);
}

export function UnenrollStudentFromClassByIDs(arg1, arg2) {
  return window['go']['main']['App']['UnenrollStudentFromClassByIDs'](arg1, arg2);
}

export function UpdateAttendanceRecord(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['UpdateAttendanceRecord'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function UpdateAttendanceTime(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateAttendanceTime'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateClass(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['UpdateClass'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function UpdateDepartment(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateDepartment'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateUser(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14) {
  return window['go']['main']['App']['UpdateUser'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14);
}

export function UpdateUserPhoto(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateUserPhoto'](arg1, arg2, arg3);
}
