// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangePassword(arg1, arg2, arg3) {
  return window['go']['main']['App']['ChangePassword'](arg1, arg2, arg3);
}

export function CreateAdmin(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateAdmin'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateInstructor(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateInstructor'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateStudent(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateStudent'](arg1, arg2, arg3, arg4);
}

export function CreateSubject(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateSubject'](arg1, arg2, arg3, arg4);
}

export function CreateUser(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11) {
  return window['go']['main']['App']['CreateUser'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
}

export function CreateWorkingStudent(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateWorkingStudent'](arg1, arg2, arg3, arg4);
}

export function DeleteUser(arg1) {
  return window['go']['main']['App']['DeleteUser'](arg1);
}

export function ExportAttendanceCSV(arg1) {
  return window['go']['main']['App']['ExportAttendanceCSV'](arg1);
}

export function ExportUsersCSV() {
  return window['go']['main']['App']['ExportUsersCSV']();
}

export function GetAdminDashboard() {
  return window['go']['main']['App']['GetAdminDashboard']();
}

export function GetFeedback() {
  return window['go']['main']['App']['GetFeedback']();
}

export function GetInstructorDashboard(arg1) {
  return window['go']['main']['App']['GetInstructorDashboard'](arg1);
}

export function GetStudentDashboard(arg1) {
  return window['go']['main']['App']['GetStudentDashboard'](arg1);
}

export function GetSubjects() {
  return window['go']['main']['App']['GetSubjects']();
}

export function GetUserByID(arg1) {
  return window['go']['main']['App']['GetUserByID'](arg1);
}

export function GetUsers() {
  return window['go']['main']['App']['GetUsers']();
}

export function GetWorkingStudentDashboard() {
  return window['go']['main']['App']['GetWorkingStudentDashboard']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function LoginByEmail(arg1, arg2) {
  return window['go']['main']['App']['LoginByEmail'](arg1, arg2);
}

export function LoginByStudentID(arg1, arg2) {
  return window['go']['main']['App']['LoginByStudentID'](arg1, arg2);
}

export function RecordAttendance(arg1, arg2, arg3) {
  return window['go']['main']['App']['RecordAttendance'](arg1, arg2, arg3);
}

export function SubmitFeedback(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SubmitFeedback'](arg1, arg2, arg3, arg4);
}

export function UpdateUser(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11) {
  return window['go']['main']['App']['UpdateUser'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
}
