// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ChangePassword(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CreateSubject(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function CreateUser(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string,arg10:string,arg11:string):Promise<void>;

export function DeleteUser(arg1:number):Promise<void>;

export function ExportAttendanceCSV(arg1:number):Promise<string>;

export function ExportFeedbackCSV():Promise<string>;

export function ExportFeedbackPDF():Promise<string>;

export function ExportLogsCSV():Promise<string>;

export function ExportLogsPDF():Promise<string>;

export function GetAdminDashboard():Promise<main.AdminDashboard>;

export function GetAllLogs():Promise<Array<main.LoginLog>>;

export function GetClassStudents(arg1:number):Promise<Array<main.ClassStudent>>;

export function GetFeedback():Promise<Array<main.Feedback>>;

export function GetStudentDashboard(arg1:number):Promise<main.StudentDashboard>;

export function GetStudentFeedback(arg1:number):Promise<Array<main.Feedback>>;

export function GetStudentLoginLogs(arg1:number):Promise<Array<main.LoginLog>>;

export function GetSubjects():Promise<Array<main.Subject>>;

export function GetTeacherDashboard(arg1:string):Promise<main.TeacherDashboard>;

export function GetUsers():Promise<Array<main.User>>;

export function GetUsersByType(arg1:string):Promise<Array<main.User>>;

export function GetWorkingStudentDashboard():Promise<main.WorkingStudentDashboard>;

export function Login(arg1:string,arg2:string):Promise<main.User>;

export function Logout(arg1:number):Promise<void>;

export function RecordAttendance(arg1:number,arg2:number,arg3:string):Promise<void>;

export function SaveEquipmentFeedback(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string,arg10:string,arg11:string):Promise<void>;

export function SearchUsers(arg1:string,arg2:string):Promise<Array<main.User>>;

export function UpdateUser(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string,arg10:string,arg11:string):Promise<void>;

export function UpdateUserPhoto(arg1:number,arg2:string,arg3:string):Promise<void>;
